### ISSUE TITLE
Extend support for self-hosted Gnosis Safe to xDAI

### ISSUE THREAD

**Issue by SCBuergel** [hoprnet/gnosis-hosted#3]
Currently we use Gnosis Safe on main net and have a [fully self-hosted setup for that](https://github.com/hoprnet/gnosis-hosted). Since HOPR Association also manages funds on the xDAI chain, we should migrate those funds also from the deprecated Gnosis Wallet to Gnosis Safe. Some tasks that this entails are
- [ ] setup an xDAI node
- [ ] link node with Gnosis Safe UI
- [ ] test the setup with test accounts moving some tokens around

**Comment by tolbrino** [comment]
@SCBuergel We didn't further discuss this. How pressing is it?

**Comment by 0xjjpa** [comment]
@tolbrino @SCBuergel can we create a bounty or reach the Gnosis Safe team to get some support here. Otherwise, I feel we should move it to Icebox for the time being until we are ready to plan for this to happen, which I feel won't be the case for Q1.

**Comment by tolbrino** [comment]
> @tolbrino @SCBuergel can we create a bounty or reach the Gnosis Safe team to get some support here. Otherwise, I feel we should move it to Icebox for the time being until we are ready to plan for this to happen, which I feel won't be the case for Q1.

This is not related to anything needed from the Gnosis team. We'd just have to set it up as described.

**Comment by 0xjjpa** [comment]
@tolbrino Gotcha, misread the task. Either way doesn't sound like something for Q1 and might be worth moving to `icebox` for future sprints.
